# Directory containing text files with links (one per line)
links_directory: "./links"

# Temporary directory for storing downloaded files
temp_directory: "./temp"

# Output directories
captures_directory: "./captures"
pcap_output_directory: "./captures/pcap"
csv_output_directory: "./captures/csv"
data_directory: "./data"
png_output_directory: "./data/png"
label_output_directory: "./data/labels"

# QUIC packet capture duration in seconds
capture_duration: 5

# Network interface to capture on (e.g., eth0, wlan0)
network_interface: "eth0"

# Delay before starting capture (to allow browser setup)
warmup_time: 2

# default is 64x64 square image
image_size: 32 
# config.yaml
wait_timeout: 10  

test_size: 0.2

random_state: 42